# Generated by Django 5.0.4 on 2024-05-23 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0005_reportcard'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reportcard',
            unique_together={('student_rank', 'date_of_reportCard_generation')},
        ),
    ]
