# Generated by Django 5.0.4 on 2024-05-23 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0006_alter_reportcard_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcard',
            name='date_of_reportCard_generation',
            field=models.DateField(auto_now_add=True),
        ),
    ]
