# Generated by Django 5.0.4 on 2024-05-04 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_students_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='file',
        ),
        migrations.RemoveField(
            model_name='students',
            name='image',
        ),
    ]
